### ISSUE TITLE
Clustering?

### ISSUE THREAD

**Issue by pritwish** [rouyang2017/SISSO#7] opened 2018-12-27 10:40 UTC
Hello Dr. Ouyang,

We know that this code can perform classification tasks, but is there a scope for performing clustering exercise with this code?

**Comment by rouyang2017** [comment] 2018-12-27 21:18
Hi! You can find the Appendix and Supplementary_Information of the SISSO paper for the metal-insulator classification data and details for exercise.  Also, you can go to https://analytics-toolkit.nomad-coe.eu/home/ for the tutorials (select method 'SISSO' from the filter).

**Comment by rouyang2017** [comment] 2019-01-04 13:11
1. (20,80) is correct for your case!  ( ...), (...) means a different thing. Each bracket represent one map with n categories (n>=2). In case of many brackets, it means you are doing multi-task learning using SISSO, i.e., finding a common descriptor for many maps. We have just submitted the MT-SISSO paper yesterday, and a new version of SISSO code will be released in few days.

2. In the paper, the I was put there just because the operator set is a set.  In the code, the operation for I is simply to let Phi_n to include Phi_(n-1) for any n.

3. The '2' in '#H2' means binary, and so #H2 means the number of binary operators. The size for Phi_n stated in the paper is a roughly guess, and there may be many redundant features to be removed.

3.1  Good question. I just checked the code, and find that the code will first check if the Phi under construction is the last space, and then decide if a feature is necessary or not to construct. For example, considering the two features: [a-b] and [b-a] for Phi02, if Phi02 is the last space (rung=2), then only one of that two feature will be constructed because the other one differ only by the sign and will make no change to your model. However, if Phi02 is not the last space (rung=3), then both [a-b] and [b-a] will be created because their make different to the generation of next-level features for Phi03, e.g. c-(a-b) is very different from c-(b-a).  Thus, you will see Phi02 is of different size for rung=2 and rung=3. 

3.2 Please note the #H2 means the number of binary operators.  In the paper we said "It is
roughly of the order of ...", and so that formula is not going to give the exact size.  The difference between that formula and the code is caused by (1) unary operators are not taken into account in that formula (2) unreasonable features such as size+energy are not to be constructed by the code (3) some useless features are not to be constructed as stated in 3.1 (4) some bad features such as divided-by-zero features, zero-features, constant-features are constructed but immediately deleted and not counted by the code.

Thank you for your questions, and hope these answers are helpful to you!

**Comment by pritwish** [comment] 2019-01-08 14:13
Thanks a ton for your continuous patient replies. The answers are definitely helping a lot. Also, can you please give a short description of what do we mean by a convex hull (or point us to some literature which gives provides an explanation about it? )

**Comment by rouyang2017** [comment] 2019-01-08 14:22
OK, here is one reference: Arthur F. Bialon, Thomas Hammerschmidt, and Ralf Drautz, Chem. Mater. 2016, 28, 2550−2556.

**Comment by pritwish** [comment] 2019-01-09 11:09
Thanks for that reference, am going through it. Similarly would you mind elaborating a bit on the Domain Overlap operation that you have followed or maybe, like above, some text which would help us with it?

**Closed** 2020-01-22 18:00 UTC
